config/routes.rb
Todoo3::Application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :todoo

  resources :subscribe

end

app/models/todoo.rb
class Todoo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		if user_signed_in?
			redirect_to :controller => 'todoo', :action => 'index'
		end
	end
end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
	before_filter :authenticate_user!

	def new
	end

	def update
		# Get the credit card details submitted by the form
		token = params[:stripeToken]

		# Create Customer
		customer = Stripe::Customer.create(
			:card => token,
			:plan => 1972,
			:email => current_user.email
			)

		current_user.subscribed = true
		current_user.stripeid = customer.id
		current_user.save

		redirect_to todoo_index_path, :notice => "Your subscription was setup! You may now access your Todoo-list."
		
	end
end

app/controllers/todoo_controller.rb
class TodooController < ApplicationController
	before_filter :authenticate_user!
	
	def index
		if !current_user.subscribed
			redirect_to new_subscribe_path, :notice => "To view the active todoos you must subscribe"
		end
		
		@todos = Todoo.where(done: false)
		@todone = Todoo.where(done: true)
	end

	def new
		@todo = Todoo.new
	end

	def todo_params
		params.require(:todoo).permit(:name, :done) 
	end

	def create
		@todo = Todoo.new(todo_params)

		if @todo.save
			redirect_to todoo_index_path, :notice => "Your todo item has been created"
		else
			render "new"
		end
	end

	def update
		@todo = Todoo.find(params[:id])

		if @todo.update_attribute(:done, true)
			redirect_to todoo_index_path, :notice => "Your todo item was marked as done!"
		else
			redirect_to todoo_index_path, :notice => "Your todo item was unable to be marked as done"
		end
	end

	def destroy
		@todo = Todoo.find(params[:id])
		@todo.destroy
	
		redirect_to todoo_index_path, :notice => "Your todo item was deleted."
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/helpers/todoo_helper.rb
module TodooHelper
end

app/views/home/index.html.erb
<h1>Todoo items</h1>

<h2>TODOO:</h2>
<% @todos.each do |t| %>
 <p>
 	<strong><%= t.name %></strong>
 	<small><%= link_to "Mark as Done", todoo_path(t), :method => :put %></small>
 </p>
<% end %>

 <h2>TODONE:</h2>

 <% @todone.each do |t| %>
   	<p>
 		<% t.name %>
 		<small><%= link_to "Remove", t, :confirm => "Is it OK to remove from the list?", :method => :delete %></small>
 	</p>
 <% end %>
<p><%= link_to "Add another item to list", new_todoo_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoo3</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if user_signed_in? %>
		You are currently signed in as <%= current_user.email %>, not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "Sign up!", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %> 
	<% end %>

	<% flash.each do |name, message| %>
		<%= content_tag :div, message, :id => "flash_#{name}" %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/subscribe/new.html.erb
<%= form_tag subscribe_path(1), :method => :put do %>
	<article>
		<label class="amount">
			<span>Amount: $9.99</span>
		</label>
	</article>

	<script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
			data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			data-description="A month's subscription"
			data-amount="999"></script>
<% end %>

app/views/todoo/index.html.erb
<h1>Todoo items</h1>

<h2>TODOO:</h2>
<% @todos.each do |t| %>
 <p>
 	<strong><%= t.name %></strong>
 	<small><%= link_to "Mark as Done", todoo_path(t), :method => :put %></small>
 </p>
<% end %>

 <h2>TODONE:</h2>

 <% @todone.each do |t| %>
   	<p>
 		<% t.name %>
 		<small><%= link_to "Remove", t, :confirm => "Is it OK to remove from the list?", :method => :delete %></small>
 	</p>
 <% end %>
<p><%= link_to "Add another item to list", new_todoo_path %></p>

app/views/todoo/new.html.erb
<h1>Add new item to your todoo-list</h1>

<%= form_for @todo, :url => todoo_index_path(@todo) do |f| %>
	<%= f.label :name %>: <%= f.text_field :name %>
	<%= f.hidden_field :done, :value => false %>
	<%= f.submit "Add to todoo list" %>
<%end%>